const products = [
    {id:1,name:"HP WireLess Mouse",desc:"Hp wireless mouse comes with 2 years of warrenty",price:450,image:"https://m.media-amazon.com/images/I/51YfiKtadEL._SL1200_.jpg",type:"Electronics",quantityInStock:7},
    {id:2,name:"Acer Aspire 7 Laptop",desc:"cer Aspire 7 laptop is powered by the latest 12th Gen Intel® Core™ processors with GeForce RTX™ 30 Series graphics for performance in application or entertainment. Maximize efficiency with performance-grade thermal solutions and comprehensive connectivity options.",price:52000,image:"https://i.gadgets360cdn.com/products/large/Acer-Aspire-7-DB-749x800-1614338241.jpg",type:"Electronics",quantityInStock:4},
    {id:3,name:"Zebronics Speakers",desc:"Zeb-Warrior is a USB powered 2.0 speaker best fit for your gaming experience as it comes in a modern design and adds an element with its breathing RGB LED lights. Connect the usb side to either laptop or through adapter to any power source and another 3.5 mm pin to music source ",price:700,image:"https://m.media-amazon.com/images/I/81grtcmxsyL._SL1500_.jpg",type:"Electronics",quantityInStock:22},
    {id:4,name:"boAt Bassheads(Jazzy Blue)",desc:"Break away from old habits through HD sound via 10mm drivers, crystal clear sound to your ears helps you execute what you have visualized perfectly, enhance your senses with the BassHeads 152. Impedance 16Ω, Sensitivity (dB) 109db ±3db, Frequency Response 20Hz-20KHz ",price:499,image:"https://m.media-amazon.com/images/I/61O8tL6wTtS._SL1500_.jpg",type:"Electronics",quantityInStock:27},
    {id:5,name:"Puma Running SHoes",desc:"Fresh. Modern. Bold. The CELL Phase running sneakers are perfect for elevating your training and your style along the way. These contemporary sneakers use CELL technology in a whole new way, with an eye-catching CELL unit at the heel for stable cushioning and a hint of streetwear-inspired flair.",price:3100,image:"https://m.media-amazon.com/images/I/71p5O9s7e8L._UL1500_.jpg",type:"Footwear",quantityInStock:12},
    {id:6,name:"Linchpin:",desc:"Seth Godin is the author of ten international bestsellers, including the New York Times bestseller The Dip.",price:350,image:"https://images-na.ssl-images-amazon.com/images/I/61MTYF-Dk+L.jpg",type:"Books",quantityInStock:120},
    {id:7,name:"Tuesdays With Morrie",desc:"Mitch Albom writes for the DETROIT FREE PRESS, and has been voted America's No. 1 sports columnist ten times by the Associated Press Sports Editors. A former professional musician, he hosts a daily radio show on WJR in Detroit.",price:250,image:"https://m.media-amazon.com/images/P/0751529818.01._SCLZZZZZZZ_SX500_.jpg",type:"Books",quantityInStock:78},
]

export default products